### ISSUE TITLE
Dependency to Windows.Storage since v3.30 threw errors

### ISSUE THREAD

**Issue by weissm** [stevencohn/OneMore#260]
**Describe the bug**
Since v3.30 the compilation of both VSS and build.ps1 threw errors due to new dependencies:

> ..\OneMore\OneMore\Commands\File\ImportWebCommand.cs(17,16,17,23): error CS0234: Der Typ- oder Namespacename "Storage" ist im Namespace "Windows" nicht vorhanden. (Möglicherweise fehlt ein Assemblyverweis.)
> ..\work\OneMore\OneMore\Commands\File\ImportWebCommand.cs(18,16,18,23): error CS0234: Der Typ- oder Namespacename "Storage" ist im Namespace "Windows" nicht vorhanden. (Möglicherweise fehlt ein Assemblyverweis.)

It is working in v3.29.1. All attempts to load windows.storage resources e.g. by nuget Microsoft.ProjectReunion did not succeed.

**To Reproduce**
1.` git clone OneMore`
2. not working: `git checkout tags/4.1 -b branch_4.1`, working: `git checkout tags/3.29.1 -b branch_3.29.1`
3. `.\build.ps1`

**Expected behavior**
see above

**Environment (if applicable):**
- Microsoft Visual Studio Community 2019, Version 16.11.2
- Microsoft .NET Framework 4.8.04084

**Comment by stevencohn** [comment]
Install the Windows 10 SDK 10.0.1904
https://developer.microsoft.com/en-US/windows/downloads/windows-10-sdk/

**Comment by weissm** [comment]
Perfect - this worked. The missing catch was in my case the need to add the following ressource to the project:
C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.20348.0\Facade\Windows.winmd
Slightly outdated info was given here:
https://blogs.windows.com/windowsdeveloper/2017/01/25/calling-windows-10-apis-desktop-application/#vZiZ96PlZUqTduts.97

**Comment by stevencohn** [comment]
Hm, yeah, the SDK has a different path on my machine. I'll add a note to the prerequisites section.
